#!/usr/bin/env bash

##? S3 bucket creation removal
##?
##? Dependencies docpars:
##?  $ brew install denisidoro/tools/docpars
##?
##? Usage:
##?     s3-bucket create [--bucket=<bucket>]
##?     s3-bucket remove [--bucket=<bucket>]
##?
##? Arguments:
##?   crete    Creates S3 bucket
##?   remove   Removes S3 bucket
##?
##? Options:
##?   -b, --bucket=<bucket>  S3 bucket name [default: aa-terraform-state-160071257600]
##?


args::parse() {
  eval "$(docpars -h "$(grep "^##?" "$0" | cut -c 5-)" : "$@")"
}

args::parse "$@"

if ${create}; then
  aws s3 mb s3://${bucket}
  if [ $? -eq 0 ]; then
    aws s3api put-bucket-encryption --bucket ${bucket} --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'
    aws s3api put-bucket-versioning --bucket ${bucket} --versioning-configuration Status=Enabled
  fi
elif ${remove}; then
  aws s3 rb s3://${bucket}
fi
