#!/usr/bin/env bash

##? ssh key tool
##?
##? Dependencies docpars:
##?  $ brew install denisidoro/tools/docpars
##?
##? Usage:
##?     ssh-keys create [--keyname=<keyname>]
##?     ssh-keys public --keyname=<keyname>
##?
##? Arguments:
##?   crete             Creates an SSH keypair
##?   public            Exports the PUBLIC key from a given private key
##?
##? Options:
##?   -k, --keyname=<keyname>  SSH key name [default: id_rsa]
##?


args::parse() {
  eval "$(docpars -h "$(grep "^##?" "$0" | cut -c 5-)" : "$@")"
}

args::parse "$@"

if ${create}; then
  ssh-keygen -t rsa -b 4096 -m pem -f ${keyname}
elif ${public}; then
  if [[ ! -f ${keyname} ]]; then
    echo "Error: ${keyname} does not exists"
    exit 1
  fi
  ssh-keygen -f ${keyname} -y 
fi
